<div class="cinema cinema-page">
    @include('partials.cinema.page-hero', ['crumb' => 'Yazılar', 'eyebrow' => 'Okuma arası / Rehberler', 'title' => 'Şehirden hikâyeler', 'description' => $directory?->editorial_voice ?: 'İşletmeler, hizmetler ve iyi kararlar üzerine güncel yazılar.'])
    <div class="cinema-wrap cinema-page__body"><form class="cinema-filter" action="{{ route('blog.index') }}" method="GET"><label>Yazılarda ara<input name="q" value="{{ request('q') }}" placeholder="Başlık veya konu"></label><button type="submit">Ara ↗</button>@if(request()->filled('q'))<a href="{{ route('blog.index') }}">Temizle</a>@endif</form>
        <div class="cinema-columns"><div class="cinema-main"><section class="cinema-panel"><div class="cinema-panel__head"><h2>Yayın seçkisi</h2><small>{{ $posts->total() }} yazı</small></div>
            @forelse($posts as $post)<article class="cinema-list-row"><a class="cinema-list-row__art" href="{{ route('blog.show',$post->slug) }}" aria-label="{{ $post->title }} yazısını aç">@if($post->image)<img src="{{ asset('storage/'.$post->image) }}" alt="{{ $post->title }}" loading="lazy">@else Y @endif</a><div><small>{{ $post->author_name ?: 'Editör' }} / {{ $post->published_at?->format('d.m.Y') }}</small><h3><a href="{{ route('blog.show',$post->slug) }}">{{ $post->title }}</a></h3><p>{{ $post->excerpt ?: \Illuminate\Support\Str::limit(strip_tags($post->content),130) }}</p></div><a class="cinema-list-row__go" href="{{ route('blog.show',$post->slug) }}">Oku ↗</a></article>@empty<div class="cinema-empty">Bu aramada yazı bulunamadı.</div>@endforelse
            @if($posts->hasPages())<div class="cinema-pagination">{{ $posts->links() }}</div>@endif
        </section></div><aside class="cinema-side"><section class="cinema-panel"><div class="cinema-panel__head"><h2>Keşfe devam</h2></div><div class="cinema-link-list"><a href="{{ route('companies.index') }}"><span>Firmalar</span><span>↗</span></a><a href="{{ route('jobs.index') }}"><span>İş ilanları</span><span>↗</span></a></div></section><div class="cinema-promo"><h2>Firmanızın hikâyesi.</h2><p>İşletme profilinizi oluşturup rehberde yer alın.</p><a class="cinema-btn" href="{{ route('owner.register') }}">Firma ekle ↗</a></div></aside></div>
    </div>
</div>
