<div class="cinema cinema-page">
    @include('partials.cinema.page-hero', ['crumb' => $category->name, 'eyebrow' => 'Sahne / Kategori', 'title' => $category->name.' firmaları', 'description' => $category->description ?: $category->name.' alanındaki işletmeleri ve hizmetleri keşfedin.'])
    <div class="cinema-wrap cinema-page__body">
        <form class="cinema-filter" action="{{ url()->current() }}" method="GET"><label>Şehir seçin<select name="city"><option value="">Tüm şehirler</option>@foreach($popularCities as $ct)<option value="{{ $ct->slug }}" @selected(request('city') == $ct->slug)>{{ $ct->name }} ({{ $ct->companies_count }})</option>@endforeach</select></label><button type="submit">Bu şehirde keşfet ↗</button>@if(request()->filled('city'))<a href="{{ url()->current() }}">Filtreyi temizle</a>@endif</form>
        <div class="cinema-columns"><div class="cinema-main">
            @include('frontend.cinema.company-list', ['listTitle' => $category->name.' seçkisi'])
            @if(!empty($seoContent))<section class="cinema-panel"><div class="cinema-panel__head"><h2>{{ $category->name }} hakkında</h2><small>Rehber</small></div><div class="cinema-copy">@foreach(explode("\n\n",$seoContent) as $paragraph)<p>{{ $paragraph }}</p>@endforeach</div></section>@endif
            @if($posts->isNotEmpty())<section class="cinema-panel"><div class="cinema-panel__head"><h2>Bu sahneden yazılar</h2></div><div class="cinema-link-list">@foreach($posts as $post)<a href="{{ route('blog.show',$post->slug) }}"><span>{{ $post->title }}</span><span>↗</span></a>@endforeach</div></section>@endif
        </div><aside class="cinema-side"><section class="cinema-panel"><div class="cinema-panel__head"><h2>Şehirler</h2><small>{{ $totalInCategory }} firma</small></div><div class="cinema-link-list">@foreach($popularCities as $ct)<a href="{{ route('cities.show',$ct->slug) }}"><span>{{ $ct->name }}</span><span>{{ $ct->companies_count }}</span></a>@endforeach</div></section><section class="cinema-panel"><div class="cinema-panel__head"><h2>Diğer kategoriler</h2></div><div class="cinema-link-list">@foreach($relatedCategories as $related)<a href="{{ route('categories.show',$related->slug) }}"><span>{{ $related->name }}</span><span>↗</span></a>@endforeach</div></section><div class="cinema-promo"><h2>Bu alanda mısınız?</h2><p>Firmanızı ekleyerek bu kategoride yer alın.</p><a class="cinema-btn" href="{{ route('owner.register') }}">Firma ekle ↗</a></div></aside></div>
    </div>
</div>
