<div class="cinema cinema-page">
    @include('partials.cinema.page-hero', ['crumb' => $city->name, 'eyebrow' => 'Rota / Şehir', 'title' => $city->name.' sahnesi', 'description' => $city->name.' içindeki işletmeleri, semtleri ve sektörleri keşfedin.'])
    <div class="cinema-wrap cinema-page__body">
        <form class="cinema-filter" action="{{ url()->current() }}" method="GET">@if($districts->isNotEmpty())<label>İlçe<select name="district"><option value="">Tüm ilçeler</option>@foreach($districts as $district)<option value="{{ $district->slug }}" @selected(request('district') == $district->slug)>{{ $district->name }}</option>@endforeach</select></label>@endif<label>Kategori<select name="category"><option value="">Tüm kategoriler</option>@foreach($popularCategories as $cat)<option value="{{ $cat->slug }}" @selected(request('category') == $cat->slug)>{{ $cat->name }}</option>@endforeach</select></label><button type="submit">Firmaları bul ↗</button>@if(request()->anyFilled(['district','category']))<a href="{{ url()->current() }}">Temizle</a>@endif</form>
        <div class="cinema-columns"><div class="cinema-main">
            @include('frontend.cinema.company-list', ['listTitle' => $city->name.' gösterimi'])
            @if(!empty($seoContent))<section class="cinema-panel"><div class="cinema-panel__head"><h2>{{ $city->name }} hakkında</h2><small>Şehir rehberi</small></div><div class="cinema-copy">@foreach(explode("\n\n",$seoContent) as $paragraph)<p>{{ $paragraph }}</p>@endforeach</div></section>@endif
            @if($posts->isNotEmpty())<section class="cinema-panel"><div class="cinema-panel__head"><h2>Şehirden yazılar</h2></div><div class="cinema-link-list">@foreach($posts as $post)<a href="{{ route('blog.show',$post->slug) }}"><span>{{ $post->title }}</span><span>↗</span></a>@endforeach</div></section>@endif
        </div><aside class="cinema-side">@if($districts->isNotEmpty())<section class="cinema-panel"><div class="cinema-panel__head"><h2>İlçeler</h2><small>Rotalar</small></div><div class="cinema-link-list">@foreach($districts->take(15) as $district)<a href="{{ url()->current() }}?district={{ $district->slug }}"><span>{{ $district->name }}</span><span>↗</span></a>@endforeach</div></section>@endif<section class="cinema-panel"><div class="cinema-panel__head"><h2>Kategoriler</h2><small>{{ $totalInCity }} firma</small></div><div class="cinema-link-list">@foreach($popularCategories as $cat)<a href="{{ route('categories.show',$cat->slug) }}"><span>{{ $cat->name }}</span><span>{{ $cat->companies_count }}</span></a>@endforeach</div></section>@if(($nearbyCities ?? collect())->isNotEmpty())<section class="cinema-panel"><div class="cinema-panel__head"><h2>Diğer şehirler</h2></div><div class="cinema-link-list">@foreach($nearbyCities as $nearby)<a href="{{ route('cities.show',$nearby->slug) }}"><span>{{ $nearby->name }}</span><span>↗</span></a>@endforeach</div></section>@endif<div class="cinema-promo"><h2>Şehirde yerinizi alın.</h2><p>Firma profilinizi oluşturun, müşteriler sizi bulsun.</p><a class="cinema-btn" href="{{ route('owner.register') }}">Firma ekle ↗</a></div></aside></div>
    </div>
</div>
