<div class="cinema cinema-page">
    @include('partials.cinema.page-hero', ['crumb' => 'İş ilanları', 'eyebrow' => 'Yeni sahne / Kariyer', 'title' => 'Açık pozisyonlar', 'description' => 'Yerel işletmelerin yayınladığı fırsatları inceleyin ve doğrudan başvurun.'])
    <div class="cinema-wrap cinema-page__body"><form class="cinema-filter" action="{{ route('jobs.index') }}" method="GET"><label>Pozisyon veya firma<input name="q" value="{{ request('q') }}" placeholder="Örneğin satış uzmanı"></label><button type="submit">İlan ara ↗</button>@if(request()->filled('q'))<a href="{{ route('jobs.index') }}">Temizle</a>@endif</form>
        <div class="cinema-columns"><div class="cinema-main"><section class="cinema-panel"><div class="cinema-panel__head"><h2>Güncel iş ilanları</h2><small>{{ $jobs->total() }} fırsat</small></div>
            @forelse($jobs as $job)<article class="cinema-list-row"><a class="cinema-list-row__art" href="{{ route('jobs.show',$job->slug) }}" aria-label="{{ $job->title }} ilanını aç">İ</a><div><small>{{ $job->company->name }} / {{ $job->location ?: $job->company->city?->name }}</small><h3><a href="{{ route('jobs.show',$job->slug) }}">{{ $job->title }}</a></h3><p>{{ \Illuminate\Support\Str::limit($job->description,135) }} · {{ $job->published_at?->format('d.m.Y') }}</p></div><a class="cinema-list-row__go" href="{{ route('jobs.show',$job->slug) }}">İlanı aç ↗</a></article>@empty<div class="cinema-empty">Şu anda açık iş ilanı bulunmuyor.</div>@endforelse
            @if($jobs->hasPages())<div class="cinema-pagination">{{ $jobs->links() }}</div>@endif
        </section></div><aside class="cinema-side"><div class="cinema-promo"><span class="cinema-kicker" style="color:#e8aa62">Sizin sahneniz</span><h2>İlan yayınlayın.</h2><p>Firmanızdaki açık pozisyonları firma panelinden ekleyin.</p><a class="cinema-btn" href="{{ route('owner.dashboard') }}">Firma paneli ↗</a></div><section class="cinema-panel"><div class="cinema-panel__head"><h2>Keşfe devam</h2></div><div class="cinema-link-list"><a href="{{ route('companies.index') }}"><span>Firmalar</span><span>↗</span></a><a href="{{ route('blog.index') }}"><span>Yazılar</span><span>↗</span></a></div></section></aside></div>
    </div>
</div>
