<div class="cinema cinema-page">
    @include('partials.cinema.page-hero', ['crumb' => $post->title, 'eyebrow' => 'Okuma arası / '.match($post->content_type){'comparison'=>'Karşılaştırma','alternatives'=>'Alternatifler','local'=>'Yerel rehber','answers'=>'Uzman cevabı','data'=>'Veri araştırması',default=>'Seçim rehberi'}, 'title' => $post->title, 'description' => $post->excerpt])
    <div class="cinema-wrap cinema-page__body"><div class="cinema-columns"><div class="cinema-main"><article class="cinema-panel cinema-article">
        <p class="cinema-kicker">{{ $post->published_at?->format('d.m.Y') }}{{ $post->author_name ? ' / '.$post->author_name : '' }}{{ $post->reviewer_name ? ' / Kontrol: '.$post->reviewer_name : '' }}</p>
        @if($post->image)<img class="cinema-article__image" src="{{ asset('storage/'.$post->image) }}" alt="{{ $post->title }}" loading="eager">@endif
        @if($blogLayout === 'comparison' && (!empty($post->pros) || !empty($post->cons)))<div class="cinema-prose"><h2>Artılar</h2><ul>@foreach($post->pros ?? [] as $item)<li>{{ $item }}</li>@endforeach</ul><h2>Eksiler</h2><ul>@foreach($post->cons ?? [] as $item)<li>{{ $item }}</li>@endforeach</ul></div>@endif
        <div class="blog-prose cinema-prose">{!! $post->content !!}</div>
        @if(!empty($post->faq_items))<div class="cinema-prose"><h2>Sık sorulanlar</h2>@foreach($post->faq_items as $faq)<details style="padding:12px 0;border-bottom:1px solid #d8c9b7"><summary style="cursor:pointer;font-weight:800">{{ $faq['question'] ?? '' }}</summary><p>{{ $faq['answer'] ?? '' }}</p></details>@endforeach</div>@endif
        @if(!empty($post->sources))<div class="cinema-prose"><h2>Kaynaklar</h2><ol>@foreach($post->sources as $source)<li><a href="{{ $source }}" target="_blank" rel="nofollow noopener">{{ $source }}</a></li>@endforeach</ol></div>@endif
    </article>@if($relatedPosts->isNotEmpty())<section class="cinema-panel"><div class="cinema-panel__head"><h2>İlgili yazılar</h2></div><div class="cinema-link-list">@foreach($relatedPosts as $related)<a href="{{ route('blog.show',$related->slug) }}"><span>{{ $related->title }}</span><span>↗</span></a>@endforeach</div></section>@endif</div><aside class="cinema-side">@if($targetCity || $targetCategory)<section class="cinema-panel"><div class="cinema-panel__head"><h2>İlgili rehberler</h2></div><div class="cinema-link-list">@if($targetCity)<a href="{{ route('cities.show',$targetCity->slug) }}"><span>{{ $targetCity->name }} firmaları</span><span>↗</span></a>@endif @if($targetCategory)<a href="{{ route('categories.show',$targetCategory->slug) }}"><span>{{ $targetCategory->name }} firmaları</span><span>↗</span></a>@endif</div></section>@endif<div class="cinema-promo"><h2>Keşfe devam.</h2><p>Yeni yazıları ve işletmeleri inceleyin.</p><a class="cinema-btn" href="{{ route('blog.index') }}">Tüm yazılar ↗</a></div></aside></div></div>
</div>
