<?php

// Active-directory theme assignments. Only matching domains are changed by the
// directories:apply-theme-plan command; unknown directories are left alone.
return [
    '81ilfirmalar.com.tr' => 'category-atlas',
    'alternatifbul.com.tr' => 'decision-desk',
    'ankarakobi.com.tr' => 'corporate',
    'buldora.com.tr' => 'orbit-directory',
    'buldunmu.com.tr' => 'signal-station',
    'esnafharita.com.tr' => 'map-directory',
    'esnafpusulasi.com.tr' => 'craft-market',
    'esnaftamyanimda.com.tr' => 'neighborhood-radar',
    'firmaendeksi.com.tr' => 'sector-exchange',
    'firmafeneri.com.tr' => 'signal-station',
    'firmahatti.com.tr' => 'service-console',
    'firmakiyasla.com.tr' => 'decision-desk',
    'firmayeri.com.tr' => 'map-directory',
    'firmondo.com.tr' => 'orbit-directory',
    'guvenilirfirmalar.com.tr' => 'verified-trust',
    'hizmetharitasi.com.tr' => 'local-map-landing',
    'hizmetyakinda.com.tr' => 'neighborhood-radar',
    'hizmetyanimda.com.tr' => 'quick-quote',
    'isletmebulutu.com.tr' => 'service-console',
    'isletmebulvar.com.tr' => 'city-board',
    'isletmelistesi.com.tr' => 'corporate',
    'isletmepusulasi.com.tr' => 'category-atlas',
    'istanbulfirmarehberi.com.tr' => 'city-journal',
    'izmirisletmeleri.com.tr' => 'paper-trail',
    'kayitlikobi.com.tr' => 'corporate',
    'kobiharita.com.tr' => 'map-directory',
    'kobiva.com.tr' => 'split-hero',
    'komsufirma.com.tr' => 'neighborhood-radar',
    'secmedenonce.com.tr' => 'decision-desk',
    'sektorbazaar.com.tr' => 'sector-exchange',
    'sektorbul.com.tr' => 'category-atlas',
    'ustaharita.com.tr' => 'craft-market',
    'ustarotasi.com.tr' => 'usta-pro',
    'yakindafirma.com.tr' => 'map-directory',
    'yereldurak.com.tr' => 'paper-trail',
    'yerelhizmetim.com.tr' => 'craft-market',
    'yerelio.com.tr' => 'premium-showcase',
    'yerelix.com.tr' => 'orbit-directory',
    'yerelrehber360.com.tr' => 'city-pulse',
    'yerelustalar.com.tr' => 'usta-pro',
];
