@extends('layouts.app')

@section('title', $settings->homepage_title ?? $settings->site_name ?? 'Brutalist Rehber')

@section('content')
<main style="background:var(--bg);">
    <section class="border-b-8" style="border-color:var(--secondary);background:var(--accent);">
        <div class="mx-auto grid gap-0 px-4 py-6 sm:px-6 lg:grid-cols-2 lg:px-8 lg:py-0" style="max-width:var(--page_width);">
            <div class="flex flex-col justify-center py-10 lg:py-20"><div class="border-4 px-3 py-2 text-xs font-black uppercase tracking-widest" style="width:max-content;border-color:var(--secondary);color:var(--secondary);">Açık işletme arşivi</div><h1 class="mt-6 max-w-xl text-5xl font-black uppercase leading-[.92] sm:text-7xl" style="color:var(--secondary);">{{ $settings->homepage_title ?? 'Firma bul. Hemen.' }}</h1><p class="mt-6 max-w-lg text-base font-bold leading-7" style="color:var(--secondary);">{{ $settings->homepage_subtitle ?? 'Şehir, kategori ve işletme bilgileri. Fazlası yok, aradığın şey var.' }}</p><form action="{{ route('search') }}" class="mt-8 flex max-w-xl border-4 bg-white p-2" style="border-color:var(--secondary);"><input name="q" class="min-w-0 flex-1 px-3 py-3 text-sm font-bold outline-none" placeholder="FİRMA / HİZMET / ŞEHİR" style="color:var(--secondary);"><button class="px-5 py-3 text-sm font-black text-white" style="background:var(--secondary);">ARA</button></form></div>
            <div class="relative min-h-80 border-4 lg:border-y-0" style="border-color:var(--secondary);"><img src="{{ asset('images/themes/local-service-street-hero.png') }}" alt="Şehirde yerel hizmet işletmesi" class="absolute inset-0 h-full w-full object-cover" width="2048" height="1152" loading="eager"><div class="absolute bottom-0 left-0 bg-white p-5 font-black uppercase" style="color:var(--secondary);">Yerel işletmeler. Gerçek iletişim.</div></div>
        </div>
    </section>
    <section class="border-b-4" style="border-color:var(--secondary);background:var(--bg_card);"><div class="mx-auto grid grid-cols-2 sm:grid-cols-4" style="max-width:var(--page_width);">@foreach([['SEKTÖR',$categories->count()],['ŞEHİR',$cities->count()],['YENİ KAYIT',$latestCompanies->count()],['BAŞVURU','+']] as [$label,$value])<div class="border-r-4 p-5 text-center last:border-r-0" style="border-color:var(--secondary);"><strong class="block text-3xl" style="color:var(--secondary);">{{ $value }}</strong><span class="mt-1 block text-xs font-black uppercase" style="color:var(--text_muted);">{{ $label }}</span></div>@endforeach</div></section>
    <section class="mx-auto px-4 py-12 sm:px-6 lg:px-8" style="max-width:var(--page_width);"><div class="mb-7 flex flex-wrap items-end justify-between gap-4"><h2 class="text-4xl font-black uppercase" style="color:var(--secondary);">Kategoriler</h2><a href="{{ route('companies.index') }}" class="border-4 px-4 py-2 text-sm font-black" style="border-color:var(--secondary);color:var(--secondary);">TÜM FİRMALAR</a></div><div class="grid border-l border-t sm:grid-cols-2 lg:grid-cols-4" style="border-color:var(--secondary);">@foreach($categories as $category)<a href="{{ route('categories.show',$category->slug) }}" class="border-b border-r p-5 transition hover:text-white" style="border-color:var(--secondary);color:var(--secondary);"><span class="text-2xl">{{ $category->icon ?? '+' }}</span><strong class="mt-8 block text-xl font-black uppercase">{{ $category->name }}</strong><small class="mt-2 block font-bold">{{ $category->companies_count }} firma</small></a>@endforeach</div></section>
    <section class="border-y-4 py-12" style="border-color:var(--secondary);background:var(--secondary);"><div class="mx-auto px-4 sm:px-6 lg:px-8" style="max-width:var(--page_width);"><div class="mb-7 flex items-end justify-between"><h2 class="text-4xl font-black uppercase text-white">Yeni firmalar</h2><a href="{{ route('owner.register') }}" class="bg-white px-4 py-3 text-sm font-black" style="color:var(--secondary);">FİRMANI EKLE</a></div><div class="grid gap-4 md:grid-cols-2">@foreach($latestCompanies->take(6) as $company)<a href="{{ route('companies.show',$company->slug) }}" class="border-4 bg-white p-5" style="border-color:var(--accent);"><div class="flex items-start gap-4"><div class="flex h-12 w-12 shrink-0 items-center justify-center bg-black text-lg font-black text-white">{{ mb_substr($company->name,0,1) }}</div><div><h3 class="font-black uppercase" style="color:var(--secondary);">{{ $company->name }}</h3><p class="mt-1 text-sm font-bold" style="color:var(--text_muted);">{{ $company->category->name ?? 'Firma' }} · {{ $company->city->name ?? 'Türkiye' }}</p></div></div></a>@endforeach</div></div></section>
    @include('partials.blog-section')
</main>
@endsection
