@extends('layouts.app')

@section('title', $settings->homepage_title ?? $settings->site_name ?? 'Karar Masası')
@section('meta_description', $settings->meta_description ?? 'Firmaları profil bilgileri, doğrulama, yorumlar ve iletişim seçenekleriyle karşılaştırın.')

@section('content')
@php $decisionCompanies = $trustedCompanies->isNotEmpty() ? $trustedCompanies->take(6) : $latestCompanies->take(6); @endphp
<div class="min-h-screen" style="background:var(--bg);">
    <section class="border-b bg-white py-12" style="border-color:var(--border);"><div class="mx-auto px-4 sm:px-6 lg:px-8" style="max-width:var(--page_width);"><div class="grid gap-8 lg:grid-cols-[1fr_360px] lg:items-end"><div><div class="text-xs font-black uppercase tracking-[0.2em]" style="color:var(--secondary);">Karar destekli firma rehberi</div><h1 class="mt-3 max-w-4xl text-4xl font-black leading-tight sm:text-5xl" style="color:var(--text);">{{ $settings->homepage_title ?? 'Seçenekleri görün, doğru firmaya güvenle karar verin' }}</h1><p class="mt-4 max-w-2xl text-base leading-7" style="color:var(--text_muted);">{{ $settings->homepage_subtitle ?? 'Firma profillerini konum, kategori, doğrulama ve iletişim bilgileriyle yan yana değerlendirin.' }}</p></div><form action="{{ route('search') }}" class="rounded-lg border p-3" style="border-color:var(--border);background:var(--primary_light);"><label class="text-xs font-black" style="color:var(--primary);">Neyi karşılaştırmak istiyorsunuz?</label><div class="mt-2 flex overflow-hidden rounded-md bg-white"><input name="q" class="min-w-0 flex-1 px-3 py-3 text-sm outline-none" placeholder="Örn. su arıtma, avukat"><button class="px-4 text-sm font-black text-white" style="background:var(--primary);">Ara</button></div></form></div></div></section>

    <section class="py-10"><div class="mx-auto px-4 sm:px-6 lg:px-8" style="max-width:var(--page_width);"><div class="mb-5 flex flex-wrap items-end justify-between gap-3"><div><div class="text-xs font-black uppercase tracking-wider" style="color:var(--accent);">Kısa liste</div><h2 class="mt-1 text-2xl font-black" style="color:var(--text);">Öne çıkan seçenekler</h2></div><a href="{{ route('companies.index') }}" class="text-sm font-black" style="color:var(--primary);">Tüm seçenekleri incele</a></div>
        <div class="overflow-x-auto rounded-lg border bg-white" style="border-color:var(--border);"><table class="w-full min-w-[760px] text-left"><thead><tr class="border-b text-xs uppercase tracking-wider" style="border-color:var(--border);color:var(--text_muted);"><th class="p-4">Firma</th><th class="p-4">Kategori</th><th class="p-4">Konum</th><th class="p-4">Doğrulama</th><th class="p-4">İletişim</th><th class="p-4"></th></tr></thead><tbody>@forelse($decisionCompanies as $company)<tr class="border-b last:border-0" style="border-color:var(--border);"><td class="p-4"><div class="flex items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-md font-black" style="background:var(--primary_light);color:var(--primary);">@if($company->logo)<img src="{{ asset('storage/'.$company->logo) }}" alt="{{ $company->name }}" class="h-full w-full object-contain">@else{{ mb_substr($company->name,0,1) }}@endif</span><strong class="max-w-[220px] truncate text-sm" style="color:var(--text);">{{ $company->name }}</strong></div></td><td class="p-4 text-sm" style="color:var(--text_muted);">{{ $company->category->name ?? '-' }}</td><td class="p-4 text-sm" style="color:var(--text_muted);">{{ $company->city->name ?? '-' }}</td><td class="p-4">@if($company->is_verified)<span class="rounded-md px-2 py-1 text-xs font-black" style="background:#e9f8ef;color:#16794a;">Doğrulanmış</span>@else<span class="text-xs" style="color:var(--text_muted);">Standart</span>@endif</td><td class="p-4 text-xs font-bold" style="color:var(--secondary);">{{ $company->phone ? 'Telefon' : ($company->whatsapp ? 'WhatsApp' : 'Profil') }}</td><td class="p-4 text-right"><a href="{{ route('companies.show',$company->slug) }}" class="rounded-md px-3 py-2 text-xs font-black text-white" style="background:var(--primary);">Profili aç</a></td></tr>@empty<tr><td colspan="6" class="p-10 text-center text-sm" style="color:var(--text_muted);">Karşılaştırılacak firma henüz yok.</td></tr>@endforelse</tbody></table></div>
    </div></section>

    <section class="border-y bg-white py-10" style="border-color:var(--border);"><div class="mx-auto px-4 sm:px-6 lg:px-8" style="max-width:var(--page_width);"><h2 class="text-xl font-black" style="color:var(--text);">Kararınızı daraltın</h2><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach($categories->take(8) as $category)<a href="{{ route('categories.show',$category->slug) }}" class="rounded-lg border p-4 transition hover:-translate-y-0.5" style="border-color:var(--border);"><span class="text-sm font-black" style="color:var(--text);">{{ $category->name }}</span><span class="mt-1 block text-xs" style="color:var(--text_muted);">{{ $category->companies_count }} seçenek</span></a>@endforeach</div></div></section>

    @if($posts->isNotEmpty())<section class="py-10"><div class="mx-auto px-4 sm:px-6 lg:px-8" style="max-width:var(--page_width);"><div class="mb-5"><div class="text-xs font-black uppercase tracking-wider" style="color:var(--secondary);">Seçmeden önce</div><h2 class="mt-1 text-2xl font-black" style="color:var(--text);">Karar rehberleri</h2></div><div class="grid gap-4 md:grid-cols-3">@foreach($posts as $post)<a href="{{ route('blog.show',$post->slug) }}" class="rounded-lg border bg-white p-5" style="border-color:var(--border);"><span class="text-xs font-bold" style="color:var(--secondary);">Rehber</span><h3 class="mt-2 font-black" style="color:var(--text);">{{ $post->title }}</h3><p class="mt-2 line-clamp-2 text-sm" style="color:var(--text_muted);">{{ $post->excerpt }}</p></a>@endforeach</div></div></section>@endif
</div>
@endsection
