@extends('layouts.app')

@section('title', $settings->homepage_title ?? $settings->site_name ?? 'Kart Mozaik')

@section('content')
@php $mosaicCompanies = $premiumCompanies->merge($latestCompanies)->unique('id')->take(7); @endphp
<main style="background:var(--bg);">
    <section class="mx-auto grid gap-4 px-4 py-5 sm:px-6 lg:grid-cols-12 lg:px-8" style="max-width:var(--page_width);">
        <article class="relative isolate min-h-96 overflow-hidden p-7 lg:col-span-7" style="background:#311250;">
            <img src="{{ asset('images/themes/city-journal-hero.png') }}" alt="Akşam yaşayan şehir merkezi" class="absolute inset-0 h-full w-full object-cover" width="2048" height="1152" loading="eager"><div class="absolute inset-0" style="background:linear-gradient(90deg,rgba(49,18,80,.92),rgba(49,18,80,.28));"></div>
            <div class="relative flex h-full max-w-xl flex-col justify-end"><div class="text-xs font-black uppercase tracking-[.2em] text-white/70">Keşif panosu</div><h1 class="mt-4 text-4xl font-black leading-tight text-white sm:text-5xl">{{ $settings->homepage_title ?? 'İyi işletmeleri bir bakışta keşfet' }}</h1><p class="mt-4 text-sm leading-7 text-white/80">{{ $settings->homepage_subtitle ?? 'Şehir, sektör ve öne çıkan firmalar için görsel keşif alanı.' }}</p><form action="{{ route('search') }}" class="mt-6 flex bg-white p-2"><input name="q" class="min-w-0 flex-1 px-3 py-2 text-sm outline-none" placeholder="Ne arıyorsun?" style="color:var(--text);"><button class="px-5 text-sm font-black text-white" style="background:var(--primary);">Ara</button></form></div>
        </article>
        <div class="grid gap-4 sm:grid-cols-2 lg:col-span-5 lg:grid-cols-2">@foreach($categories->take(4) as $category)<a href="{{ route('categories.show',$category->slug) }}" class="flex min-h-44 flex-col justify-between p-5 transition hover:-translate-y-1" style="background:{{ $loop->even ? 'var(--primary)' : 'var(--bg_card)' }};color:{{ $loop->even ? 'white' : 'var(--text)' }};box-shadow:var(--card_shadow);"><span class="text-2xl">{{ $category->icon ?? '+' }}</span><span><strong class="block text-lg">{{ $category->name }}</strong><small class="mt-1 block opacity-70">{{ $category->companies_count }} firma</small></span></a>@endforeach</div>
    </section>
    <section class="mx-auto px-4 py-10 sm:px-6 lg:px-8" style="max-width:var(--page_width);"><div class="mb-6 flex items-end justify-between"><div><div class="text-xs font-black uppercase tracking-widest" style="color:var(--accent);">Vitrin</div><h2 class="mt-2 text-3xl font-black" style="color:var(--text);">Bugünün firma seçkisi</h2></div><a href="{{ route('companies.index') }}" class="text-sm font-black" style="color:var(--primary);">Hepsini gör</a></div><div class="grid gap-4 md:grid-cols-4">@foreach($mosaicCompanies as $company)<a href="{{ route('companies.show',$company->slug) }}" class="group relative min-h-56 overflow-hidden p-5 transition hover:-translate-y-1" style="background:var(--bg_card);box-shadow:var(--card_shadow);"><div class="flex h-12 w-12 items-center justify-center rounded-full font-black text-white" style="background:var(--primary);">{{ mb_substr($company->name,0,1) }}</div><div class="absolute inset-x-5 bottom-5"><span class="text-xs font-black" style="color:var(--accent);">{{ $company->is_premium ? 'ÖNE ÇIKAN' : 'YENİ' }}</span><h3 class="mt-2 font-black" style="color:var(--text);">{{ $company->name }}</h3><p class="mt-1 text-sm" style="color:var(--text_muted);">{{ $company->category->name ?? 'Firma' }} · {{ $company->city->name ?? 'Türkiye' }}</p></div></a>@endforeach</div></section>
    @if($cities->isNotEmpty())<section class="py-12" style="background:var(--primary_light);"><div class="mx-auto px-4 sm:px-6 lg:px-8" style="max-width:var(--page_width);"><div class="mb-6 text-center"><div class="text-xs font-black uppercase tracking-widest" style="color:var(--primary);">Şehir seç</div><h2 class="mt-2 text-3xl font-black" style="color:var(--text);">Haritanı daralt</h2></div><div class="flex flex-wrap justify-center gap-3">@foreach($cities as $city)<a href="{{ route('cities.show',$city->slug) }}" class="bg-white px-5 py-3 text-sm font-black shadow-sm" style="color:var(--text);">{{ $city->name }} <small style="color:var(--primary);">{{ $city->companies_count }}</small></a>@endforeach</div></div></section>@endif
    @include('partials.blog-section')
    @include('partials.cta')
</main>
@endsection
