@extends('layouts.app')

@section('title', $settings->homepage_title ?? $settings->site_name ?? 'Firma Rehberi')
@section('meta_description', $settings->meta_description ?? 'İşletmeleri hizmet ve konuma göre keşfedin.')

@push('head')
<style>
    .orbit-directory .orbit-field { background: radial-gradient(circle at 76% 35%,rgba(144,224,208,.24),transparent 26%),radial-gradient(circle at 18% 80%,rgba(245,102,120,.16),transparent 27%),linear-gradient(135deg,var(--hero_from),var(--hero_to)); }
    .orbit-directory .orbit-ring { border:1px solid rgba(255,255,255,.22); border-radius:50%; }
    .orbit-directory .orbit-tile:hover { transform:translateY(-4px); box-shadow:var(--card_shadow); }
</style>
@endpush

@section('content')
@php $orbitCompanies = $premiumCompanies->isNotEmpty() ? $premiumCompanies->take(6) : $latestCompanies->take(6); @endphp
<main class="orbit-directory" style="background:var(--bg)">
    <section class="orbit-field overflow-hidden text-white">
        <div class="mx-auto grid min-h-[470px] gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[minmax(0,1fr)_380px] lg:items-center lg:px-8" style="max-width:var(--page_width)">
            <div><p class="mb-5 text-xs font-black uppercase tracking-[.25em]" style="color:var(--accent)">Şehir × hizmet × işletme</p><h1 class="max-w-3xl text-4xl font-black leading-tight sm:text-6xl" style="font-family:var(--font_heading)">{{ $settings->homepage_title ?? 'İyi bir keşif, doğru yerden başlar' }}</h1><p class="mt-5 max-w-xl text-base leading-7 text-white/80">{{ $settings->homepage_subtitle ?? 'Bir şehir veya hizmet seçin. Size uygun işletmeleri bulun ve profillerini karşılaştırın.' }}</p><form action="{{ route('search') }}" method="GET" role="search" class="mt-8 flex max-w-xl flex-col gap-2 rounded-2xl bg-white p-2 sm:flex-row"><label for="orbit-search" class="sr-only">Firma ara</label><input id="orbit-search" name="q" class="min-w-0 flex-1 px-4 py-3 text-sm text-slate-900 outline-none" placeholder="Ne arıyorsunuz?"><button class="rounded-xl px-6 py-3 text-sm font-black text-white" style="background:var(--secondary)">Keşfet →</button></form></div>
            <div class="relative hidden h-80 items-center justify-center lg:flex" aria-hidden="true"><div class="orbit-ring absolute h-80 w-80"></div><div class="orbit-ring absolute h-60 w-60"></div><div class="orbit-ring absolute h-40 w-40"></div><div class="flex h-28 w-28 items-center justify-center rounded-full text-center text-lg font-black" style="background:var(--accent);color:var(--primary)">{{ $directory->name ?? $settings->site_name ?? 'Keşfet' }}</div><span class="absolute left-0 top-8 rounded-full bg-white px-4 py-2 text-xs font-black" style="color:var(--primary)">Şehir</span><span class="absolute right-0 top-16 rounded-full px-4 py-2 text-xs font-black" style="background:var(--secondary)">Hizmet</span><span class="absolute bottom-4 right-6 rounded-full bg-white px-4 py-2 text-xs font-black" style="color:var(--primary)">Firma</span></div>
        </div>
    </section>
    <section class="mx-auto px-4 py-12 sm:px-6 lg:px-8" style="max-width:var(--page_width)"><div class="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-widest" style="color:var(--secondary)">1 / Konum seç</p><h2 class="mt-1 text-3xl font-black" style="font-family:var(--font_heading)">Şehirlerden başlayın</h2></div><a href="{{ route('companies.index') }}" class="text-sm font-bold underline">Bütün firmalar</a></div><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@forelse($cities->take(8) as $city)<a href="{{ route('cities.show', $city->slug) }}" class="orbit-tile flex min-h-28 flex-col justify-between rounded-3xl border bg-white p-5 transition" style="border-color:var(--border)"><span class="text-xs font-bold uppercase tracking-widest" style="color:var(--secondary)">Şehir rehberi ↗</span><span class="flex items-end justify-between gap-3"><strong class="text-xl">{{ $city->name }}</strong><small style="color:var(--text_muted)">{{ $city->companies_count }} firma</small></span></a>@empty<p class="text-sm">Henüz şehir kaydı yok.</p>@endforelse</div></section>
    <section class="border-y py-12" style="background:var(--primary_light);border-color:var(--border)"><div class="mx-auto px-4 sm:px-6 lg:px-8" style="max-width:var(--page_width)"><p class="text-xs font-black uppercase tracking-widest" style="color:var(--secondary)">2 / Hizmet seç</p><h2 class="mt-1 text-3xl font-black" style="font-family:var(--font_heading)">Aramanızı daraltın</h2><div class="mt-6 flex flex-wrap gap-3">@foreach($categories->take(12) as $category)<a href="{{ route('categories.show', $category->slug) }}" class="rounded-full border bg-white px-5 py-3 text-sm font-bold transition hover:-translate-y-1" style="border-color:var(--border)">{{ $category->name }} <span class="ml-2" style="color:var(--secondary)">↗</span></a>@endforeach</div></div></section>
    <section class="mx-auto px-4 py-12 sm:px-6 lg:px-8" style="max-width:var(--page_width)"><div class="mb-6"><p class="text-xs font-black uppercase tracking-widest" style="color:var(--secondary)">3 / Firma incele</p><h2 class="mt-1 text-3xl font-black" style="font-family:var(--font_heading)">Keşfe devam edin</h2></div><div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">@forelse($orbitCompanies as $company)<article class="orbit-tile flex flex-col rounded-3xl border bg-white p-6 transition" style="border-color:var(--border)"><div class="flex items-start justify-between gap-4"><span class="flex h-14 w-14 items-center justify-center rounded-2xl text-2xl font-black" style="background:var(--primary_light);color:var(--primary)">@if($company->logo)<img src="{{ asset('storage/'.$company->logo) }}" alt="" class="h-full w-full rounded-2xl object-contain">@else{{ mb_substr($company->name,0,1) }}@endif</span><span class="text-xs font-bold" style="color:var(--text_muted)">{{ $company->city->name ?? 'Türkiye' }}</span></div><p class="mt-6 text-xs font-black uppercase tracking-widest" style="color:var(--secondary)">{{ $company->category->name ?? 'İşletme' }}</p><h3 class="mt-1 text-xl font-black">{{ $company->name }}</h3><p class="mt-2 line-clamp-2 flex-1 text-sm leading-6" style="color:var(--text_muted)">{{ $company->short_description ?: 'İşletme profilini ve iletişim bilgilerini inceleyin.' }}</p><a href="{{ route('companies.show', $company->slug) }}" class="mt-5 border-t pt-4 text-sm font-black" style="border-color:var(--border);color:var(--primary)">Profili görüntüle →</a></article>@empty<p class="text-sm">Henüz firma kaydı yok.</p>@endforelse</div></section>
    @include('partials.blog-section')
    @include('partials.cta')
</main>
@endsection
