@extends('layouts.app')

@section('title', $settings->homepage_title ?? $settings->site_name ?? 'Yerel Pazar')

@section('content')
<main style="background:var(--bg);">
    <section class="relative isolate overflow-hidden" style="min-height:590px;background:#174d36;">
        <img src="{{ asset('images/themes/local-service-street-hero.png') }}" alt="Yerel işletmelerin bulunduğu sokak" class="absolute inset-0 h-full w-full object-cover" width="2048" height="1152" loading="eager">
        <div class="absolute inset-0" style="background:linear-gradient(90deg,rgba(18,67,46,.92),rgba(18,67,46,.53));"></div>
        <div class="relative mx-auto grid min-h-[590px] items-end gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:px-8" style="max-width:var(--page_width);">
            <div class="pb-5"><div class="inline-flex bg-white/15 px-3 py-1.5 text-xs font-black uppercase tracking-[.2em] text-white">Mahalleden seçilmiş</div><h1 class="mt-6 max-w-3xl text-4xl font-black leading-tight text-white sm:text-6xl">{{ $settings->homepage_title ?? 'Yakınındaki iyi işletmeleri keşfet' }}</h1><p class="mt-5 max-w-xl text-base leading-8 text-white/85">{{ $settings->homepage_subtitle ?? 'Yerel hizmetleri, ustaları ve bağımsız markaları tek bir doğal akışta bul.' }}</p><form action="{{ route('search') }}" class="mt-8 flex max-w-xl overflow-hidden bg-white p-2 shadow-2xl"><input name="q" class="min-w-0 flex-1 border-0 px-4 py-3 text-sm outline-none" placeholder="Ne arıyorsun?" style="color:var(--text);"><button class="px-6 text-sm font-black text-white" style="background:var(--accent);">Keşfet</button></form></div>
            <div class="grid grid-cols-2 gap-3 sm:max-w-md lg:justify-self-end">@foreach($categories->take(6) as $category)<a href="{{ route('categories.show',$category->slug) }}" class="border bg-white/95 p-4 transition hover:-translate-y-1" style="border-color:rgba(255,255,255,.5);"><span class="text-xl">{{ $category->icon ?? '+' }}</span><strong class="mt-7 block text-sm" style="color:var(--text);">{{ $category->name }}</strong><small class="mt-1 block" style="color:var(--text_muted);">{{ $category->companies_count }} firma</small></a>@endforeach</div>
        </div>
    </section>

    <section class="py-14"><div class="mx-auto grid gap-10 px-4 sm:px-6 lg:grid-cols-[.75fr_1.25fr] lg:px-8" style="max-width:var(--page_width);"><div><div class="text-xs font-black uppercase tracking-[.18em]" style="color:var(--accent);">Yerel seçki</div><h2 class="mt-3 text-4xl font-black" style="color:var(--text);">Sokağın iyi işletmeleri</h2><p class="mt-4 max-w-sm leading-7" style="color:var(--text_muted);">Yeni, faydalı ve doğrudan ulaşılabilir işletmeleri bir arada tutan mahalle rehberi.</p><a href="{{ route('listing.create') }}" class="mt-7 inline-flex px-5 py-3 text-sm font-black text-white" style="background:var(--primary);">İşletmeni ekle</a></div><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach($premiumCompanies->merge($latestCompanies)->unique('id')->take(6) as $company)<a href="{{ route('companies.show',$company->slug) }}" class="group bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div class="flex items-center justify-between"><span class="text-xs font-black" style="color:var(--accent);">{{ $company->is_premium ? 'ÖNE ÇIKAN' : 'YEREL' }}</span><span class="text-lg" style="color:var(--primary);">{{ mb_substr($company->name,0,1) }}</span></div><h3 class="mt-10 font-black" style="color:var(--text);">{{ $company->name }}</h3><p class="mt-2 text-sm" style="color:var(--text_muted);">{{ $company->category->name ?? 'Firma' }} · {{ $company->city->name ?? 'Türkiye' }}</p><span class="mt-6 block text-xs font-black" style="color:var(--primary);">PROFİLİ GÖR</span></a>@endforeach</div></div></section>

    @if($cities->isNotEmpty())<section class="py-12" style="background:var(--primary);"><div class="mx-auto px-4 sm:px-6 lg:px-8" style="max-width:var(--page_width);"><div class="mb-6 flex items-end justify-between"><div><div class="text-xs font-black uppercase tracking-widest text-white/60">Şehirler</div><h2 class="mt-2 text-3xl font-black text-white">Yakınındaki pazarı seç</h2></div><a href="{{ route('companies.index') }}" class="text-sm font-black text-white">Tüm firmalar</a></div><div class="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">@foreach($cities as $city)<a href="{{ route('cities.show',$city->slug) }}" class="border border-white/20 bg-white/10 p-4 text-sm font-black text-white transition hover:bg-white/20">{{ $city->name }} <small class="mt-1 block text-white/60">{{ $city->companies_count }} kayıt</small></a>@endforeach</div></div></section>@endif
    @include('partials.blog-section')
    @include('partials.cta')
</main>
@endsection
