@extends('layouts.app')

@section('title', $settings->homepage_title ?? $settings->site_name ?? 'Terminal Rehber')

@section('content')
<main class="min-h-screen px-3 py-4 sm:px-6 sm:py-8" style="background:var(--bg);">
    <div class="mx-auto overflow-hidden border" style="max-width:var(--page_width);border-color:var(--border);box-shadow:var(--card_shadow);">
        <div class="flex items-center justify-between border-b px-4 py-3 text-xs" style="background:#080d09;border-color:var(--border);color:var(--text_muted);"><span>rehber@yerel:~$</span><span>{{ now()->format('Y-m-d H:i') }}</span></div>
        <section class="border-b p-5 sm:p-8" style="background:var(--bg_card);border-color:var(--border);">
            <div class="text-sm" style="color:var(--secondary);">$ rehber --ara --yerel</div>
            <h1 class="mt-5 max-w-4xl text-3xl font-black leading-tight sm:text-5xl" style="color:var(--text);">{{ $settings->homepage_title ?? 'İşletme verisini doğrudan bul.' }}</h1>
            <p class="mt-4 max-w-2xl text-sm leading-7" style="color:var(--text_muted);">{{ $settings->homepage_subtitle ?? 'Şehir, kategori ve güncel profil bilgileri üzerinden hızlı arama deneyimi.' }}</p>
            <form action="{{ route('search') }}" class="mt-7 flex max-w-3xl border p-1" style="border-color:var(--border);background:#080d09;"><span class="px-3 py-3 text-sm" style="color:var(--secondary);">$</span><input name="q" class="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none" placeholder="firma veya kategori yaz" style="color:var(--text);"><button class="border px-5 text-sm font-black" style="border-color:var(--primary);background:var(--primary);color:#061209;">ÇALIŞTIR</button></form>
        </section>

        <section class="grid border-b lg:grid-cols-[1.2fr_.8fr]" style="border-color:var(--border);">
            <div class="border-b p-5 sm:p-8 lg:border-b-0 lg:border-r" style="border-color:var(--border);"><div class="flex items-center justify-between"><h2 class="text-sm font-black" style="color:var(--secondary);">./son_eklenenler</h2><a href="{{ route('companies.index') }}" class="text-xs font-black" style="color:var(--accent);">TÜMÜ</a></div><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[560px] text-left text-sm"><thead class="text-xs uppercase" style="color:var(--text_muted);"><tr><th class="pb-3">#</th><th class="pb-3">Firma</th><th class="pb-3">Sektör</th><th class="pb-3">Konum</th></tr></thead><tbody class="divide-y" style="border-color:var(--border);">@forelse($latestCompanies->take(8) as $company)<tr><td class="py-3" style="color:var(--secondary);">{{ str_pad((string) ($loop->index + 1), 2, '0', STR_PAD_LEFT) }}</td><td class="py-3 font-black"><a href="{{ route('companies.show',$company->slug) }}">{{ $company->name }}</a></td><td class="py-3" style="color:var(--text_muted);">{{ $company->category->name ?? '-' }}</td><td class="py-3" style="color:var(--text_muted);">{{ $company->city->name ?? '-' }}</td></tr>@empty<tr><td colspan="4" class="py-8 text-center" style="color:var(--text_muted);">Henüz kayıt yok.</td></tr>@endforelse</tbody></table></div></div>
            <aside class="p-5 sm:p-8" style="background:#080d09;"><div class="text-xs font-black uppercase" style="color:var(--secondary);">Sistem özeti</div><div class="mt-5 grid grid-cols-2 gap-px border" style="border-color:var(--border);background:var(--border);"><div class="p-4" style="background:var(--bg_card);"><strong class="block text-2xl" style="color:var(--text);">{{ $categories->count() }}</strong><span class="text-xs" style="color:var(--text_muted);">Kategoriler</span></div><div class="p-4" style="background:var(--bg_card);"><strong class="block text-2xl" style="color:var(--text);">{{ $cities->count() }}</strong><span class="text-xs" style="color:var(--text_muted);">Şehirler</span></div><div class="p-4" style="background:var(--bg_card);"><strong class="block text-2xl" style="color:var(--text);">{{ $premiumCompanies->count() }}</strong><span class="text-xs" style="color:var(--text_muted);">Öne çıkan</span></div><a href="{{ route('listing.create') }}" class="p-4 text-sm font-black" style="background:var(--primary);color:#061209;">+ Kayıt ekle</a></div></aside>
        </section>

        <section class="p-5 sm:p-8" style="background:var(--bg_card);"><div class="flex items-center justify-between"><h2 class="text-sm font-black" style="color:var(--secondary);">./kategoriler</h2><span class="text-xs" style="color:var(--text_muted);">KOMUT SEÇ</span></div><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($categories as $category)<a href="{{ route('categories.show',$category->slug) }}" class="border p-4 transition hover:border-current" style="border-color:var(--border);"><span class="text-xs" style="color:var(--secondary);">cat /{{ $category->slug }}</span><strong class="mt-3 block" style="color:var(--text);">{{ $category->name }}</strong><small class="mt-1 block" style="color:var(--text_muted);">{{ $category->companies_count }} sonuç</small></a>@endforeach</div></section>
    </div>
</main>
@endsection
