@extends('layouts.app')

@section('title', $settings->homepage_title ?? $settings->site_name ?? 'Zaman Akışı')

@section('content')
<main style="background:var(--bg);">
    <section class="border-b" style="background:var(--bg_card);border-color:var(--border);">
        <div class="mx-auto grid gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_360px] lg:px-8" style="max-width:var(--page_width);">
            <div><div class="text-xs font-black uppercase tracking-[.2em]" style="color:var(--primary);">Canlı kayıt akışı</div><h1 class="mt-4 max-w-3xl text-4xl font-black leading-tight sm:text-5xl" style="color:var(--text);">{{ $settings->homepage_title ?? 'Bugün rehbere eklenen işletmeleri takip edin' }}</h1><p class="mt-4 max-w-2xl text-base leading-7" style="color:var(--text_muted);">{{ $settings->homepage_subtitle ?? 'Yeni firmalar, doğrulanan profiller ve popüler sektörler kronolojik olarak burada.' }}</p></div>
            <form action="{{ route('search') }}" class="self-end border p-2 shadow-sm" style="border-color:var(--border);background:var(--bg);"><label class="block px-3 pb-2 text-xs font-black uppercase tracking-wider" style="color:var(--text_muted);">Akışta ara</label><div class="flex"><input name="q" class="min-w-0 flex-1 bg-transparent px-3 py-2 text-sm outline-none" placeholder="Firma ya da hizmet"><button class="px-5 py-2 text-sm font-black text-white" style="background:var(--primary);">Ara</button></div></form>
        </div>
    </section>

    <section class="mx-auto grid gap-10 px-4 py-12 sm:px-6 lg:grid-cols-[minmax(0,1fr)_280px] lg:px-8" style="max-width:var(--page_width);">
        <div><div class="mb-7 flex items-center justify-between"><div><div class="text-xs font-black uppercase tracking-widest" style="color:var(--accent);">{{ now()->translatedFormat('d F Y') }}</div><h2 class="mt-2 text-3xl font-black" style="color:var(--text);">Yeni işletme hareketleri</h2></div><a href="{{ route('companies.index') }}" class="text-sm font-black" style="color:var(--primary);">Tüm akış</a></div>
            <div class="relative space-y-5 border-l pl-7" style="border-color:var(--border);">@forelse($latestCompanies as $company)<article class="relative border bg-white p-5 shadow-sm" style="border-color:var(--border);"><span class="absolute -left-[2.1rem] top-6 h-3 w-3 rounded-full border-4" style="border-color:var(--bg);background:var(--primary);"></span><div class="flex flex-wrap items-center justify-between gap-3"><span class="text-xs font-black uppercase tracking-wider" style="color:var(--primary);">Yeni kayıt</span><time class="text-xs" style="color:var(--text_muted);">{{ optional($company->created_at)->translatedFormat('H:i') }}</time></div><div class="mt-3 flex items-start gap-4"><div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full text-lg font-black text-white" style="background:var(--primary);">{{ mb_substr($company->name,0,1) }}</div><div class="min-w-0 flex-1"><h3 class="font-black" style="color:var(--text);"><a href="{{ route('companies.show',$company->slug) }}">{{ $company->name }}</a></h3><p class="mt-1 text-sm" style="color:var(--text_muted);">{{ $company->category->name ?? 'Firma' }} · {{ $company->city->name ?? 'Türkiye' }}</p>@if($company->short_description)<p class="mt-3 line-clamp-2 text-sm leading-6" style="color:var(--text_muted);">{{ $company->short_description }}</p>@endif</div></div></article>@empty<div class="border bg-white p-8 text-sm" style="border-color:var(--border);color:var(--text_muted);">Akış için ilk firma kaydı bekleniyor.</div>@endforelse</div>
        </div>
        <aside class="space-y-5"><div class="border bg-white p-5" style="border-color:var(--border);"><div class="text-xs font-black uppercase tracking-wider" style="color:var(--primary);">Bugünün başlıkları</div><div class="mt-4 space-y-3">@foreach($categories->take(6) as $category)<a href="{{ route('categories.show',$category->slug) }}" class="flex items-center justify-between border-b pb-3 text-sm font-black last:border-0 last:pb-0" style="border-color:var(--border);color:var(--text);"><span>{{ $category->name }}</span><small style="color:var(--primary);">{{ $category->companies_count }}</small></a>@endforeach</div></div><div class="border p-5" style="border-color:var(--border);background:var(--primary);"><span class="text-xs font-black uppercase tracking-wider text-white/65">Firma sahipleri</span><strong class="mt-3 block text-xl text-white">Akışa katılın</strong><p class="mt-2 text-sm leading-6 text-white/75">Firmanızın güncel bilgilerini ekleyin ve profilinizi tamamlayın.</p><a href="{{ route('listing.create') }}" class="mt-5 inline-flex bg-white px-4 py-2 text-sm font-black" style="color:var(--primary);">Firma ekle</a></div></aside>
    </section>
    @include('partials.blog-section')
</main>
@endsection
