@extends('layouts.app')

@section('title', $settings->homepage_title ?? $settings->site_name ?? 'Güven Endeksi Firma Rehberi')
@section('meta_description', $settings->meta_description ?? 'Doğrulanmış firma bilgileri, onaylı kullanıcı yorumları ve profil doluluk puanlarıyla işletmeleri karşılaştırın.')

@section('content')
@php $trustList = $trustedCompanies->isNotEmpty() ? $trustedCompanies : $latestCompanies->take(8); @endphp

<main style="background:var(--bg);">
    <section class="border-b py-14" style="border-color:var(--border);background:var(--bg_card);"><div class="mx-auto grid gap-10 px-4 sm:px-6 lg:grid-cols-[1fr_0.75fr] lg:px-8" style="max-width:var(--page_width,1200px);"><div><div class="text-xs font-black uppercase tracking-[0.2em]" style="color:var(--primary);">Şeffaf firma karşılaştırması</div><h1 class="mt-4 text-4xl font-black leading-tight sm:text-6xl" style="color:var(--text);">{{ $settings->homepage_title ?? 'Güvenebileceğiniz firmayı verilerle bulun' }}</h1><p class="mt-5 max-w-2xl text-base leading-8" style="color:var(--text_muted);">{{ $settings->homepage_subtitle ?? 'Doğrulanmış bilgiler, gerçek yorumlar ve güncel profil verileriyle daha bilinçli seçim yapın.' }}</p><form action="{{ route('search') }}" method="GET" class="mt-7 flex max-w-2xl overflow-hidden rounded-md border" style="border-color:var(--border);"><input name="q" class="min-w-0 flex-1 px-5 py-4 outline-none" placeholder="Firma veya hizmet ara..." style="background:var(--bg);color:var(--text);"><button class="px-7 font-black text-white" style="background:var(--primary);">Karşılaştır</button></form></div><div class="grid grid-cols-2 gap-px overflow-hidden rounded-lg border" style="border-color:var(--border);background:var(--border);"><div class="p-5" style="background:var(--bg);"><strong class="text-3xl" style="color:var(--primary);">{{ $trustedCompanies->count() }}</strong><span class="mt-1 block text-xs" style="color:var(--text_muted);">Doğrulanmış firma</span></div><div class="p-5" style="background:var(--bg);"><strong class="text-3xl" style="color:var(--primary);">{{ $trustList->sum('approved_reviews_count') }}</strong><span class="mt-1 block text-xs" style="color:var(--text_muted);">Onaylı yorum</span></div><div class="col-span-2 p-5" style="background:var(--bg);"><strong class="text-lg" style="color:var(--text);">Puan nasıl oluşur?</strong><p class="mt-2 text-xs leading-6" style="color:var(--text_muted);">Profil doluluğu %45, kullanıcı puanı %35, admin doğrulaması %20 ağırlığındadır.</p></div></div></div></section>

    <section class="py-12"><div class="mx-auto px-4 sm:px-6 lg:px-8" style="max-width:var(--page_width,1200px);"><div class="mb-8 flex items-end justify-between gap-4"><div><div class="text-xs font-black uppercase tracking-[0.2em]" style="color:var(--primary);">Güven sıralaması</div><h2 class="mt-2 text-3xl font-black" style="color:var(--text);">Öne çıkan firma profilleri</h2></div><a href="{{ route('companies.index') }}" class="text-sm font-black" style="color:var(--primary);">Tümünü gör</a></div><div class="grid gap-5 md:grid-cols-2">
        @foreach($trustList as $company)
            @php
                $profileScore = $company->profileCompletionScore();
                $ratingScore = $company->reviews_avg_rating ? ((float)$company->reviews_avg_rating / 5) * 100 : 0;
                $trustScore = min(100, (int) round(($profileScore * .45) + ($ratingScore * .35) + ($company->is_verified ? 20 : 0)));
            @endphp
            <article class="rounded-lg border p-5 shadow-sm" style="border-color:var(--border);background:var(--bg_card);"><div class="flex gap-4"><a href="{{ route('companies.show',$company->slug) }}" class="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-md text-xl font-black text-white" style="background:var(--primary);">@if($company->logo)<img src="{{ asset('storage/'.$company->logo) }}" alt="{{ $company->name }}" class="h-full w-full bg-white object-contain p-1">@else{{ mb_substr($company->name,0,1) }}@endif</a><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><a href="{{ route('companies.show',$company->slug) }}" class="truncate font-black" style="color:var(--text);">{{ $company->name }}</a>@if($company->is_verified)<span class="rounded-full px-2 py-1 text-[10px] font-black text-white" style="background:var(--primary);">DOĞRULANDI</span>@endif</div><p class="mt-1 text-xs" style="color:var(--text_muted);">{{ $company->category->name ?? 'Firma' }} · {{ $company->city->name ?? 'Türkiye' }}</p></div><div class="text-right"><strong class="text-3xl" style="color:var(--primary);">{{ $trustScore }}</strong><span class="block text-[10px] font-black" style="color:var(--text_muted);">GÜVEN</span></div></div><div class="mt-5 h-2 overflow-hidden rounded-full" style="background:var(--primary_light);"><div class="h-full rounded-full" style="width:{{ $trustScore }}%;background:var(--primary);"></div></div><div class="mt-4 grid grid-cols-3 divide-x text-center" style="border-color:var(--border);"><div><strong class="block text-sm" style="color:var(--text);">{{ $company->reviews_avg_rating ? number_format((float)$company->reviews_avg_rating,1) : '–' }}</strong><span class="text-[10px]" style="color:var(--text_muted);">Puan</span></div><div><strong class="block text-sm" style="color:var(--text);">{{ $company->approved_reviews_count }}</strong><span class="text-[10px]" style="color:var(--text_muted);">Yorum</span></div><div><strong class="block text-sm" style="color:var(--text);">%{{ $profileScore }}</strong><span class="text-[10px]" style="color:var(--text_muted);">Profil</span></div></div><div class="mt-4 flex items-center justify-between border-t pt-4 text-xs" style="border-color:var(--border);color:var(--text_muted);"><span>Güncelleme: {{ $company->updated_at->format('d.m.Y') }}</span><a href="{{ route('companies.show',$company->slug) }}" class="font-black" style="color:var(--primary);">Profili incele</a></div></article>
        @endforeach
    </div></div></section>

    <section class="border-y py-12" style="border-color:var(--border);background:var(--bg_card);"><div class="mx-auto grid gap-5 px-4 sm:px-6 md:grid-cols-3 lg:px-8" style="max-width:var(--page_width,1200px);"><div class="border-t-4 p-5" style="border-color:var(--primary);background:var(--bg);"><h3 class="font-black" style="color:var(--text);">Doğrulanmış bilgiler</h3><p class="mt-2 text-sm leading-6" style="color:var(--text_muted);">Admin kontrolünden geçen firma profilleri açıkça işaretlenir.</p></div><div class="border-t-4 p-5" style="border-color:var(--accent);background:var(--bg);"><h3 class="font-black" style="color:var(--text);">Onaylı yorumlar</h3><p class="mt-2 text-sm leading-6" style="color:var(--text_muted);">Yalnızca moderasyondan geçen değerlendirmeler puana katılır.</p></div><div class="border-t-4 p-5" style="border-color:#16a34a;background:var(--bg);"><h3 class="font-black" style="color:var(--text);">Güncel profiller</h3><p class="mt-2 text-sm leading-6" style="color:var(--text_muted);">Profil doluluğu ve son güncelleme tarihi kullanıcıya gösterilir.</p></div></div></section>
    @include('partials.blog-section')
    @include('partials.cta')
</main>
@endsection
